# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5896a5a86035bfe1ba5c21eab3bb82f684994a06f3f3c3b3bfe8bf9874ab6f83d39046715e5fde5f4759a950bc6dbdf17391a9082503dd9b25b03ed72a9316c1

test:
  secret_key_base: 66181b40798f366117470df738f6f5c466619f542578fe5b64aca233095d079ec7af7e13d500832835aa70c3be0d638d5ce372b578bd2def2c62fdde2a6496b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
